drop table if exists REVENUE;
drop table if exists STOCK;
drop table if exists ORDER_DETAIL;
drop table if exists ORDER_;
drop table if exists LOCATION;
drop table if exists CUSTOMER;
drop table if exists PRODUCT;
drop table if exists PRODUCT_CATEGORY;
drop table if exists SUPPLIER;

create table customer (id integer not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), username varchar(255), primary key (id));
create table location (id integer not null, address_city varchar(255), address_country varchar(255), address_county varchar(255), address_street_address varchar(255), name varchar(255), primary key (id));
create table order_ (id integer not null, address_city varchar(255), address_country varchar(255), address_county varchar(255), address_street_address varchar(255), created_at timestamp, customer_id integer, shipped_from_id integer, primary key (id));
create table order_detail (id integer not null, quantity integer, order_id integer, product_id integer, primary key (id));
create table product (id integer not null, description varchar(255), image_url varchar(255), name varchar(255), price decimal(19,2), weight double, category_id integer, supplier_id integer, primary key (id));
create table product_category (id integer not null, description varchar(255), name varchar(255), primary key (id));
create table revenue (id integer not null, date date, sum decimal(19,2), location_id integer, primary key (id));
create table stock (id integer not null, quantity integer, location_id integer, product_id integer, primary key (id));
create table supplier (id integer not null, name varchar(255), primary key (id));
alter table order_ add constraint FKbcqs50rf794der0iy0h6c0mgd foreign key (customer_id) references customer;
alter table order_ add constraint FKf5oqqh9fkxnxoaccb3xixnxf3 foreign key (shipped_from_id) references location;
alter table order_detail add constraint FK4u34rkhbehcj1jbb1mc5m8ccs foreign key (order_id) references order_;
alter table order_detail add constraint FKb8bg2bkty0oksa3wiq5mp5qnc foreign key (product_id) references product;
alter table product add constraint FK5cypb0k23bovo3rn1a5jqs6j4 foreign key (category_id) references product_category;
alter table product add constraint FK2kxvbr72tmtscjvyp9yqb12by foreign key (supplier_id) references supplier;
alter table revenue add constraint FK6xukepd8ssa1ok6iakkhp83p7 foreign key (location_id) references location;
alter table stock add constraint FK6t3m0kaf6fubuus331gf7xmn8 foreign key (location_id) references location;
alter table stock add constraint FKjghkvw2snnsr5gpct0of7xfcf foreign key (product_id) references product;